// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package query

import (
	"context"

	"github.com/sqlc-dev/pqtype"
)

const createServiceLog = `-- name: CreateServiceLog :exec
INSERT INTO service_logs (
  service_name, metadata
) VALUES (
  $1, $2
)
`

type CreateServiceLogParams struct {
	ServiceName string
	Metadata    pqtype.NullRawMessage
}

func (q *Queries) CreateServiceLog(ctx context.Context, arg CreateServiceLogParams) error {
	_, err := q.db.ExecContext(ctx, createServiceLog, arg.ServiceName, arg.Metadata)
	return err
}
